[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Lasso = "b4fcebef-c861-5a0f-a7e2-ba9dc32b180a"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
