[deps]
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
